<a href="https://colab.research.google.com/github/DK0806/2311MC20/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

change notebook settings to GPU

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 00 . Pytorch fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have question : https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.3.1+cu121


### Introduction to tensors

Creating tensors

Pytorch tensors are created using torch.tensor() = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
 scalar.item()
 scalar.shape

torch.Size([])

In [ ]:
### Vector ###

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

## dimension is no of pair of square brackets

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
### MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
### Tensor

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[7,6,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [7, 6, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

### IT SAYS WE GOT ONE 3 BY 3 SHAPE TENSOR

torch.Size([1, 3, 3])

 ### RANDOM TENSORS

 WHY RANDOM TENSORS ?

 Random tensors are important because the way neural netwk learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent data



 `start with random numbers  -> look at data -> update random numbers -> look at data -> update random numbers



 Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1882, 0.0847, 0.3167, 0.3113],
        [0.8508, 0.8039, 0.2268, 0.5513],
        [0.8295, 0.6531, 0.5246, 0.8630]])

In [ ]:
random_tensor.ndim

2

In [ ]:
## create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,224,224))  # size=(height , width , no of color channel(R,G,B))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeroes and ones

In [ ]:
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeroes * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors like

In [ ]:
torch.range(0,10)

<ipython-input-21-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
 # to use torch.range() WE USE arange()
one_to_ten = torch.arange(start=0 , end = 11 , step = 0.5)
one_to_ten

tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,
         4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,
         8.0000,  8.5000,  9.0000,  9.5000, 10.0000, 10.5000])

In [ ]:
#### creating a tensor like

ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes

** **Note :**. Tensor dataype is one of the 3 big errors u will run into pytorch & deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,5.0],
                               dtype = None         # what datatype is the tensor
                               , device = None      # what device your tensor is on
                               , requires_grad = False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 5.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 25.])

### GETTING INFORMATION FROM TENSORS

1. Tensor not right datatype - to get datatype from a tensor use tensor.dtype
2. Tensor not right shape - to get shape from tensor use tensor.shape
3. Tensor not on right device - to get device from a tensor use tensor.device

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5419, 0.0963, 0.4955, 0.4125],
        [0.2959, 0.2472, 0.6643, 0.1885],
        [0.8199, 0.3920, 0.8926, 0.9094]])

### Matrix multiplication

two ways :

1) element wise



2) Matrix Multiplication (dot product)


Rules to satisfy matrix multiplication :

1) The **inner dimension must match** :
> (3,2) @ (3,2) wont work
> (2,3) @ (3,2)  work
>  (3,2) @ (2,3)  work


2) THE RESULTING MATRIX HAS SHAPE OF OUTER DIMENSION

> (2,3) @ (3,2) -> (2,2)
> (3,2) @ (2,3) -> (3,3)

In [34]:
#element wise multiplication

print(tensor ,'*', tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [35]:
# Matrix multiplication
torch.matmul(tensor , tensor)

tensor(14)

In [36]:
# matrix multiplication hard coded

1*1 + 2*2 + 3*3

14

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.65 ms, sys: 2.1 ms, total: 3.75 ms
Wall time: 4.35 ms


In [38]:
%%time
torch.matmul(tensor , tensor)

CPU times: user 743 µs, sys: 0 ns, total: 743 µs
Wall time: 613 µs


tensor(14)

In [39]:
# one more way for matmul

tensor @ tensor

tensor(14)

In [40]:
# matrix mul rule 1 ex

torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
see the difference above and below

In [41]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5176, 0.1625, 0.4597],
        [0.7225, 0.3384, 0.1865],
        [0.2466, 0.0882, 0.1751]])

One of the most common errors in deep learning : shape error


In [42]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A , tensor_B)

# torch .mm is same as torch.matmul

torch.matmul(tensor_A , tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [43]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix out shape issue , we can manipulate the shape of one of our tensor using transpose

In [44]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [45]:
tensor_B , tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [50]:
output = torch.mm(tensor_A , tensor_B.T)
output

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [51]:
output.shape

torch.Size([3, 3])

### Finding the min , max , mean , sum  








**TENSOR Aggregation**


In [52]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# find min
torch.min(x), min(x)


tensor(0)

In [58]:
#find max

torch.max(x), max(x)

(tensor(90), tensor(90))

In [59]:
#find mean

# here we got error because of dtype i.e., most common error in pytorch
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [60]:
x.dtype

torch.int64

In [63]:
#finding the mean
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Finding the positional min and max

In [65]:
# Find the position in tensor that has minimum value in
# argmin() -> returns index position of target tensor
# where minmum value occurs


x.argmin()

tensor(0)

In [66]:
# Find the position in tensor that has maximum value in
# argmax() -> returns index position of target tensor
# where max value occurs

x.argmax()

tensor(9)

In [67]:
x[9]

tensor(90)

### RESHAPING , STACKING , SQUEEZING & UNSQUEEZING TENSORS